{% set name = "stochatreat" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6265dd194eee74e0ea24c3edf53440d4253fa4523b5cf35ee7a6c29a2b66fa2
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - hatch
    - pandas
    - numpy
  run:
    - python >=3.6
    - pip
    - hatch
    - pandas
    - numpy

test:
  imports:
    - stochatreat

about:
  home: http://github.com/manmartgarc/stochatreat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module for block randomization using pandas

  description: |
    stochatreat is a Python module to employ block randomization using pandas.
    Mainly thought with RCTs in mind, it also works for any other scenario in
    where you would like to randomly allocate treatment within blocks or strata.
  dev_url: https://github.com/manmartgarc/stochatreat

extra:
  recipe-maintainers:
    - manmartgarc
    - royalts
