{% set name = "stochatreat" %}
{% set version = "0.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9aff791e059d4023d6b634f8eb2c0d3403232f01133f7760b38f9f16aefec22a
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatch
    - pandas
    - numpy
  run:
    - python >={{ python_min }}
    - pip
    - hatch
    - pandas
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - stochatreat

about:
  home: http://github.com/manmartgarc/stochatreat
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module for block randomization using pandas

  description: |
    stochatreat is a Python module to employ block randomization using pandas.
    Mainly thought with RCTs in mind, it also works for any other scenario in
    where you would like to randomly allocate treatment within blocks or strata.
  dev_url: https://github.com/manmartgarc/stochatreat

extra:
  recipe-maintainers:
    - manmartgarc
    - royalts
